# Generated by Django 4.2.1 on 2023-06-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=80)),
                ('fabricante', models.CharField(max_length=80)),
                ('municion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TParma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTP', models.CharField(max_length=60)),
            ],
        ),
    ]
